# Generated by Django 3.2.9 on 2021-12-03 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='users/avatars/', verbose_name='Аватар')),
                ('mobile_phone', models.CharField(help_text='Номер мобильного телефона', max_length=17)),
                ('city_phone', models.CharField(help_text='Номер городского телефона', max_length=7)),
                ('hobby', models.TextField()),
                ('skills', models.TextField()),
                ('interests', models.TextField()),
                ('experience', models.IntegerField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', related_query_name='employee', to='project.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
