# Generated by Django 3.2.9 on 2021-12-03 07:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(help_text='Номер мобильного телефона', max_length=17, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть введен в формате: "+999999999". Максимальная длина номера - 15 символов.', regex='^\\+?1?\\d{9,15}$')])),
                ('city_phone', models.CharField(help_text='Номер городского телефона', max_length=7, validators=[django.core.validators.RegexValidator(message='Номер городского телефона должен быть введен в формате: "2999999". Максимальная длина номера - 7 символов.', regex='^\\2?1?\\d{9,6}$')])),
                ('hobby', models.TextField()),
                ('skills', models.TextField()),
                ('interests', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
