# Generated by Django 3.2.9 on 2021-12-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='city_phone',
            field=models.CharField(help_text='Номер городского телефона', max_length=7),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_phone',
            field=models.CharField(help_text='Номер мобильного телефона', max_length=17),
        ),
    ]
