from django.db import models


class Task(models.Model):
    """Общая шаблонная инфа по задаче"""
    title = models.CharField(max_length=128)
    description = models.TextField()
    project = ...
    tags = ...
    verifiability = models.BooleanField()
    experience = ...
    achievements = ...
    in_course = models.BooleanField()


class UserTask(models.Model):
    """Инфа по задаче, персонализированная для конкретного юзера"""
    result = ...
    deadline = ...
    perfect_deadline = ...
    responsible = ...
    task = ...
    user = ...


class TaskResult(models.Model):
    """Результат выполнения задачи"""
    user_task = ...
    status = ...
    estimation = ...
    description = ...
