from django.db import models
from django.contrib.auth.models import User


class Employee(models.Model):
    img = ...
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE, related_name="employee")
    mobile_phone = ...
    city_phone = ...
    hobby = ...
    skills = ...
    interests = ...
    position = ...
    achievements = ...
    experience = ...
