# Generated by Django 3.2.9 on 2021-12-03 14:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название статьи проекта', max_length=40)),
                ('content', models.TextField(help_text='Описание статьи')),
                ('resource_link', models.URLField(help_text='Ссылка на ресурс статьи', max_length=100, null=True)),
                ('video_link', models.URLField(help_text='Ссылка на видео-описание ресурса', max_length=100, null=True)),
                ('next', models.ForeignKey(blank=True, help_text='Следующая статья в списке', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prevful', to='project.article')),
                ('prev', models.ForeignKey(blank=True, help_text='Предыдущая статья в списке', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nextful', to='project.article')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название проекта', max_length=100)),
                ('purpose', models.TextField(help_text='Цель(-ли) проекта')),
                ('issue', models.TextField(help_text='Задача(-и) проекта')),
                ('managment_info', models.TextField(help_text='Обязательные мероприятия по скраму')),
                ('calendar_info', models.TextField(help_text='План работ и контрольные точки')),
                ('result_info', models.TextField(help_text='Результаты проекта')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ФИО участника команды', max_length=40)),
                ('specialization', models.CharField(help_text='Компетенция участника команды', max_length=40)),
                ('telegram', models.CharField(help_text='Контакты участника в телеграм', max_length=40)),
                ('mail', models.EmailField(help_text='Почта участника', max_length=40)),
                ('phone', models.CharField(help_text='Номер телефона участника', max_length=17, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть введен в формате: "+999999999". Максимальная длина номера - 15 символов.', regex='^\\+?1?\\d{9,15}$')])),
                ('project', models.ForeignKey(blank=True, help_text='Проект участника команды', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', related_query_name='member', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название ресурса под ссылку', max_length=50)),
                ('comment', models.CharField(blank=True, help_text='Комментарий к связке статей', max_length=100)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_hints', to='project.article')),
                ('target', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_hint', to='project.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=project.models.article_directory_path)),
                ('article', models.ForeignKey(blank=True, help_text='Файлы конкретной статьи', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', related_query_name='file', to='project.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Проект, в котором содержится эта статья', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', related_query_name='article', to='project.project'),
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='Ссылка на ресурс в IDM', max_length=100)),
                ('template_content', models.TextField(help_text='Заготовка заявки на получение доступа')),
                ('article', models.OneToOneField(blank=True, help_text='Ресурс проекта', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access', related_query_name='access', to='project.article')),
            ],
        ),
    ]
