# Generated by Django 3.2.9 on 2021-12-03 11:35

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название статьи проекта', max_length=40)),
                ('content', models.TextField(help_text='Описание статьи')),
                ('resource_link', models.URLField(help_text='Ссылка на ресурс статьи', max_length=100, null=True)),
                ('video_link', models.URLField(help_text='Ссылка на видео-описание ресурса', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=project.models.article_directory_path)),
                ('article', models.ForeignKey(help_text='Файлы конкретной статьи', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', related_query_name='file', to='project.article')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название ресурса под ссылку', max_length=50)),
                ('comment', models.CharField(blank=True, help_text='Комментарий к связке статей', max_length=100)),
                ('source_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='project.article')),
                ('target_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='project.article')),
            ],
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='resource',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.AddField(
            model_name='article',
            name='linked_articles',
            field=models.ManyToManyField(help_text='Связанные по информации статьи', through='project.LinkedArticles', to='project.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='next',
            field=models.ForeignKey(help_text='Следующая статья в списке', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prevful', to='project.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='prev',
            field=models.ForeignKey(help_text='Предыдущая статья в списке', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nextful', to='project.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='project',
            field=models.ForeignKey(help_text='Проект, в котором содержится эта статья', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', related_query_name='article', to='project.project'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='article',
            field=models.OneToOneField(help_text='Ресурс проекта', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access', related_query_name='access', to='project.article'),
        ),
    ]
