# Generated by Django 3.2.9 on 2021-12-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video_link',
            field=models.TextField(help_text='Ссылка на видео-описание ресурса', max_length=100, null=True),
        ),
    ]
