# Generated by Django 3.2.9 on 2021-12-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_article_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='resource_link_1',
            field=models.URLField(blank=True, help_text='Ссылка на ресурс статьи', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='resource_link_2',
            field=models.URLField(blank=True, help_text='Ссылка на ресурс статьи', max_length=100, null=True),
        ),
    ]
