# Generated by Django 3.2.9 on 2021-12-03 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20211203_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название ресурса под ссылку', max_length=50)),
                ('comment', models.CharField(blank=True, help_text='Комментарий к связке статей', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='linked_articles',
        ),
        migrations.DeleteModel(
            name='LinkedArticles',
        ),
        migrations.AddField(
            model_name='hint',
            name='target_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='project.article'),
        ),
    ]
