# Generated by Django 3.2.9 on 2021-12-03 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20211203_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hint',
            name='target_article',
        ),
        migrations.AddField(
            model_name='hint',
            name='hint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hinted', to='project.article'),
        ),
        migrations.AddField(
            model_name='hint',
            name='hinted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hint', to='project.article'),
        ),
    ]
