# Generated by Django 3.2.9 on 2021-12-03 21:35

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_articlefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlefile',
            name='file',
            field=models.FileField(upload_to=project.models.article_directory_path),
        ),
    ]
