# Generated by Django 3.2.9 on 2021-12-03 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20211203_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hint',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='hint',
            name='hinted',
        ),
        migrations.AddField(
            model_name='hint',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_hints', to='project.article'),
        ),
        migrations.AddField(
            model_name='hint',
            name='target',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_hint', to='project.article'),
        ),
    ]
