# Generated by Django 3.2.9 on 2021-12-03 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20211203_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='article',
            field=models.OneToOneField(blank=True, help_text='Ресурс проекта', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access', related_query_name='access', to='project.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='next',
            field=models.ForeignKey(blank=True, help_text='Следующая статья в списке', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prevful', to='project.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='prev',
            field=models.ForeignKey(blank=True, help_text='Предыдущая статья в списке', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nextful', to='project.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Проект, в котором содержится эта статья', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', related_query_name='article', to='project.project'),
        ),
        migrations.AlterField(
            model_name='articlefile',
            name='article',
            field=models.ForeignKey(blank=True, help_text='Файлы конкретной статьи', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', related_query_name='file', to='project.article'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_hints', to='project.article'),
        ),
        migrations.AlterField(
            model_name='hint',
            name='target',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_hint', to='project.article'),
        ),
        migrations.AlterField(
            model_name='member',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Проект участника команды', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', related_query_name='member', to='project.project'),
        ),
    ]
